version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb+srv://priyagosai:admin123@cluster0.6p8fw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=ABCDEFGHIJKLMNOPQRSTUVWXYZ
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
